# Compare results from the Token Classification with other sources
Getting the data from the repo: https://github.com/JUrban/extract-defs/tree/main/lm-inputs/defsCT

In [1]:
import re
import os
from os.path import join

from transformers import (AutoTokenizer,
                         TFAutoModelForTokenClassification,)

cfg = {'checkpoint': 'bert-base-uncased',
      'max_length': 150, # check mp_infer_HFTrans_ner.py
      }

/home/luis/code/arxivDownload/venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
xdefs_root = join(os.path.expanduser('~'),'zornMedia/extract-defs')
xdefs_inputs = join(xdefs_root, 'lm-inputs/defsCT')
xdefs_outputs = join(xdefs_root, 'lm-outputs/defsCT')
xdefs_inputs_filelst = sorted(os.listdir(xdefs_inputs))
xdefs_outputs_filelst = sorted(os.listdir(xdefs_outputs))

with open(join(xdefs_outputs, xdefs_outputs_filelst[0]), 'r') as fobj:
    xdefs_out_lst = fobj.readlines()
with open(join(xdefs_inputs, xdefs_inputs_filelst[0]), 'r') as fobj:
    xdefs_in_lst = fobj.readlines()

In [3]:
# Example to grab 'Definition 8.1: DEFINES "taxotopic"\n'
# and 'Definition 7.2: DEFINES "taxotopic", "S-taxotopic", "taxotopy equivalent", "S-taxotopy equivalent", "null-taxotopic"\n'
#reg_expr = re.compile('Definition[\s\d\.\:]+DEFINES\s+"(.+?)"+')
reg_expr = re.compile('"(.+?)"+')
def get_term(out_str):
    # The out_str is the output string produced by the LLM
    Defin = reg_expr.findall(out_str)
    return Defin

reg_expr2 = re.compile('Definition\s+[\d\.]+\s+(.+)')
def get_text(in_str):
    Defin = reg_expr2.findall(in_str)
    return Defin
get_text(xdefs_in_lst[15])    

['A reduced SC type $n$-operad in a symmetric monoidal category $V$ is a collection $A_{T}\\in V$ where $T$ runs over all coloured pruned $n$-trees such that $A_{U^{1}_{n}}=A_{U^{2}_{n}}=I$ and $A_{z^{n}U_{0}}=I,$ where $U^{1}_{n}$ is a linear tree with its unique tip coloured by $1$ and $U^{2}_{n}$ is a linear tree with its tip coloured by $2.$ This collection is equipped with a morphism $m_{\\sigma}:A_{S}\\otimes A_{T_{1}^{(p)}}\\otimes\\ldots\\otimes A_{T_{k}^{(p)}}% \\rightarrow A_{T}$ for every coloured morphism of trees $\\sigma:T\\rightarrow S$ between coloured pruned $n$-trees. They must satisfy the obvious associativity and unitarity conditions. For an unbased reduced SC-operad we use collections without degenerate trees and define multiplication only with respect to surjections of coloured trees.']

In [4]:
tokenizer = AutoTokenizer\
          .from_pretrained(cfg['checkpoint'])

In [5]:
tokenizer(xdefs_in_lst[15][:100],
         return_tensors='tf',
         is_split_into_words=False,
         padding=True,
         truncation=True,
         max_length=cfg['max_length'])

2024-08-05 03:42:05.173600: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-08-05 03:42:05.175761: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-08-05 03:42:05.183593: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-05 03:42:05.197704: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-05 03:42:05.201749: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-05 03:42:05.212345: I tensorflow/core/platform/cpu_feature_gu

{'input_ids': <tf.Tensor: shape=(1, 31), dtype=int32, numpy=
array([[  101,  6210,  1023,  1012,  1017,  1037,  4359,  8040,  2828,
         1002,  1050,  1002,  1011,  3850,  2094,  1999,  1037, 19490,
        18847, 16975,  4696,  1002,  1058,  1002,  2003,  1037,  3074,
         1002,  1037,  1035,   102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 31), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 31), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [9]:
xdefs_in_lst[15]

'Definition 9.3 A reduced SC type $n$-operad in a symmetric monoidal category $V$ is a collection $A_{T}\\in V$ where $T$ runs over all coloured pruned $n$-trees such that $A_{U^{1}_{n}}=A_{U^{2}_{n}}=I$ and $A_{z^{n}U_{0}}=I,$ where $U^{1}_{n}$ is a linear tree with its unique tip coloured by $1$ and $U^{2}_{n}$ is a linear tree with its tip coloured by $2.$ This collection is equipped with a morphism $m_{\\sigma}:A_{S}\\otimes A_{T_{1}^{(p)}}\\otimes\\ldots\\otimes A_{T_{k}^{(p)}}% \\rightarrow A_{T}$ for every coloured morphism of trees $\\sigma:T\\rightarrow S$ between coloured pruned $n$-trees. They must satisfy the obvious associativity and unitarity conditions. For an unbased reduced SC-operad we use collections without degenerate trees and define multiplication only with respect to surjections of coloured trees.\n'